<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MotorPix.Arquitetura.Testes</RootNamespace>
    <AssemblyName>MotorPix.Arquitetura.Testes</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MotorPix.Dominio\MotorPix.Dominio.csproj" />
  </ItemGroup>

</Project>
