<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MotorPix.Psp.Nucleo</RootNamespace>
    <AssemblyName>MotorPix.Psp.Nucleo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MotorPix.Dominio\MotorPix.Dominio.csproj" />
    <ProjectReference Include="..\MotorPix.Mensagens\MotorPix.Mensagens.csproj" />
    <ProjectReference Include="..\MotorPix.Contratos\MotorPix.Contratos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MotorPix.Psp.Nucleo.Testes" />
  </ItemGroup>

</Project>
